package com.htn.colorcall.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "BACKGROUND".
 */
@Entity
public class Background {

    @Id(autoincrement = true)
    private Long id;
    private int type;

    @NotNull
    private String pathThumb;

    @NotNull
    private String pathItem;
    private boolean delete;

    @Generated(hash = 2094308092)
    public Background() {
    }

    public Background(Long id) {
        this.id = id;
    }

    @Generated(hash = 1724201483)
    public Background(Long id, int type, @NotNull String pathThumb, @NotNull String pathItem,
            boolean delete) {
        this.id = id;
        this.type = type;
        this.pathThumb = pathThumb;
        this.pathItem = pathItem;
        this.delete = delete;
    }

    public Background(int type, String pathThumb, String pathItem, boolean delete) {
        this.type = type;
        this.pathThumb = pathThumb;
        this.pathItem = pathItem;
        this.delete = delete;
    }
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    @NotNull
    public String getPathThumb() {
        return pathThumb;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPathThumb(@NotNull String pathThumb) {
        this.pathThumb = pathThumb;
    }

    @NotNull
    public String getPathItem() {
        return pathItem;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPathItem(@NotNull String pathItem) {
        this.pathItem = pathItem;
    }

    public boolean getDelete() {
        return delete;
    }

    public void setDelete(boolean delete) {
        this.delete = delete;
    }

}
