package com.colorcall.callerscreen.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BACKGROUND".
*/
public class BackgroundDao extends AbstractDao<Background, Long> {

    public static final String TABLENAME = "BACKGROUND";

    /**
     * Properties of entity Background.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Type = new Property(1, int.class, "type", false, "TYPE");
        public final static Property PathThumb = new Property(2, String.class, "pathThumb", false, "PATH_THUMB");
        public final static Property PathItem = new Property(3, String.class, "pathItem", false, "PATH_ITEM");
        public final static Property Delete = new Property(4, boolean.class, "delete", false, "DELETE");
    }


    public BackgroundDao(DaoConfig config) {
        super(config);
    }
    
    public BackgroundDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BACKGROUND\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TYPE\" INTEGER NOT NULL ," + // 1: type
                "\"PATH_THUMB\" TEXT NOT NULL ," + // 2: pathThumb
                "\"PATH_ITEM\" TEXT NOT NULL ," + // 3: pathItem
                "\"DELETE\" INTEGER NOT NULL );"); // 4: delete
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BACKGROUND\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Background entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getType());
        stmt.bindString(3, entity.getPathThumb());
        stmt.bindString(4, entity.getPathItem());
        stmt.bindLong(5, entity.getDelete() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Background entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getType());
        stmt.bindString(3, entity.getPathThumb());
        stmt.bindString(4, entity.getPathItem());
        stmt.bindLong(5, entity.getDelete() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Background readEntity(Cursor cursor, int offset) {
        Background entity = new Background( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // type
            cursor.getString(offset + 2), // pathThumb
            cursor.getString(offset + 3), // pathItem
            cursor.getShort(offset + 4) != 0 // delete
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Background entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType(cursor.getInt(offset + 1));
        entity.setPathThumb(cursor.getString(offset + 2));
        entity.setPathItem(cursor.getString(offset + 3));
        entity.setDelete(cursor.getShort(offset + 4) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Background entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Background entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Background entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
