package com.colorcall.callerscreen.database;

import com.google.gson.annotations.SerializedName;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "BACKGROUND".
 */
@Entity
public class Background {
    @SerializedName("type")
    private int type;
    @SerializedName("path-thumb")
    @NotNull
    private String pathThumb;

    @SerializedName("path-file")
    @NotNull
    private String pathItem;

    @Id(autoincrement = true)
    private Long id;
    private boolean delete;
    @SerializedName("name")
    @NotNull
    private String name;
    @SerializedName("time_update")
    @NotNull
    private String time_update;
    private int position;
    @Generated
    public Background() {
    }

    public Background(Long id) {
        this.id = id;
    }

    public Background( int type, @NotNull String pathThumb, @NotNull String pathItem,
                      boolean delete,String name,int position) {
        this.type = type;
        this.pathThumb = pathThumb;
        this.pathItem = pathItem;
        this.delete = delete;
        this.name = name;
        this.position = position;
    }
    public Background(int type, @NotNull String pathThumb, @NotNull String pathItem,
                      boolean delete) {
        this.type = type;
        this.pathThumb = pathThumb;
        this.pathItem = pathItem;
        this.delete = delete;
    }

    @Generated
    public Background( Long id,int type, @NotNull String pathThumb, @NotNull String pathItem,
            boolean delete) {
        this.type = type;
        this.pathThumb = pathThumb;
        this.pathItem = pathItem;
        this.id = id;
        this.delete = delete;
    }
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    @NotNull
    public String getPathThumb() {
        return pathThumb;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPathThumb(@NotNull String pathThumb) {
        this.pathThumb = pathThumb;
    }

    @NotNull
    public String getPathItem() {
        return pathItem;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPathItem(@NotNull String pathItem) {
        this.pathItem = pathItem;
    }

    public boolean getDelete() {
        return delete;
    }

    public void setDelete(boolean delete) {
        this.delete = delete;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getPosition() {
        return position;
    }

    public void setPosition(int position) {
        this.position = position;
    }

    public String getTime_update() {
        return time_update;
    }

    public void setTime_update(String time_update) {
        this.time_update = time_update;
    }

    @Override
    public String toString() {
        return "Background{" +
                "type=" + type +
                ", pathThumb='" + pathThumb + '\'' +
                ", pathItem='" + pathItem + '\'' +
                ", id=" + id +
                ", delete=" + delete +
                ", name='" + name + '\'' +
                ", time_update='" + time_update + '\'' +
                ", position=" + position +
                '}';
    }
}
