package com.colorcall.callerscreen.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CONTACT".
 */
@Entity
public class Contact {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String contact_id;

    @NotNull
    private String background_path;

    @NotNull
    private String background;

    @Generated
    public Contact() {
    }

    public Contact(Long id) {
        this.id = id;
    }

    @Generated
    public Contact(Long id, String contact_id, String background_path, String background) {
        this.id = id;
        this.contact_id = contact_id;
        this.background_path = background_path;
        this.background = background;
    }
    public Contact( String contact_id, String background_path, String background) {
        this.contact_id = contact_id;
        this.background_path = background_path;
        this.background = background;
    }
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getContact_id() {
        return contact_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContact_id(@NotNull String contact_id) {
        this.contact_id = contact_id;
    }

    @NotNull
    public String getBackground_path() {
        return background_path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBackground_path(@NotNull String background_path) {
        this.background_path = background_path;
    }

    @NotNull
    public String getBackground() {
        return background;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBackground(@NotNull String background) {
        this.background = background;
    }

}
