package com.colorcall.callerscreen.database;

import com.colorcall.callerscreen.model.Background;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig backgroundDaoConfig;

    private final BackgroundDao backgroundDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        backgroundDaoConfig = daoConfigMap.get(BackgroundDao.class).clone();
        backgroundDaoConfig.initIdentityScope(type);

        backgroundDao = new BackgroundDao(backgroundDaoConfig, this);

        registerDao(Background.class, backgroundDao);
    }
    
    public void clear() {
        backgroundDaoConfig.clearIdentityScope();
    }

    public BackgroundDao getBackgroundDao() {
        return backgroundDao;
    }

}
