package com.colorcall.callerscreen.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.colorcall.callerscreen.database.Background;
import com.colorcall.callerscreen.database.Contact;

import com.colorcall.callerscreen.database.BackgroundDao;
import com.colorcall.callerscreen.database.ContactDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig backgroundDaoConfig;
    private final DaoConfig contactDaoConfig;

    private final BackgroundDao backgroundDao;
    private final ContactDao contactDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        backgroundDaoConfig = daoConfigMap.get(BackgroundDao.class).clone();
        backgroundDaoConfig.initIdentityScope(type);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        backgroundDao = new BackgroundDao(backgroundDaoConfig, this);
        contactDao = new ContactDao(contactDaoConfig, this);

        registerDao(Background.class, backgroundDao);
        registerDao(Contact.class, contactDao);
    }
    
    public void clear() {
        backgroundDaoConfig.clearIdentityScope();
        contactDaoConfig.clearIdentityScope();
    }

    public BackgroundDao getBackgroundDao() {
        return backgroundDao;
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

}
