package com.colorcall.callerscreen.analystic;

public interface EventKey {
    String SPLASH_OPEN = "SPLASH_OPEN";
    String SPLASH_START_CLICKED = "SPLASH_START_CLICKED";

    String MAIN_OPEN = "MAIN_OPEN";
    String MAIN_SLIDEMENU_CLICKED = "MAIN_SLIDEMENU_CLICKED";
    String MAIN_STAR_CLICKED = "MAIN_STAR_CLICKED";
    String MAIN_ADSBOX_CLICKED = "MAIN_ADSBOX_CLICKED";
    String MAIN_CAMERA_CLICKED = "MAIN_CAMERA_CLICKED";
    String MAIN_SEEALLRECOMMEND_CLICKED = "MAIN_SEEALLRECOMMEND_CLICKED";
    String MAIN_SEEALLPOPULAR_CLICKED = "MAIN_SEEALLPOPULAR_CLICKED";
    String MAIN_SEEALLYOURTHEME_CLICKED = "MAIN_SEEALLYOURTHEME_CLICKED";
    String MAIN_SEEALLCOLOREFFECT_CLICKED = "MAIN_SEEALLCOLOREFFECT_CLICKED";
    String MAIN_SEEALLLOVELY_CLICKED = "MAIN_SEEALLLOVELY_CLICKED";
    String MAINDIALOG_OPEN = "MAINDIALOG_OPEN";
    String MAINDIALOG_VIDEOS_CLICKED  = "MAINDIALOG_VIDEOS_CLICKED";
    String MAINDIALOG_IMAGES_CLICKED  = "MAINDIALOG_IMAGES_CLICKED";

    String SEEMORE_OPEN = "SEEMORE_OPEN";
    String SEEMORE_BACK_CLICKED  = "SEEMORE_BACK_CLICKED";
    String SEEMORE_CAMERA_CLICKED  = "SEEMORE_CAMERA_CLICKED";

    String APPLY_OPEN = "APPLY_OPEN";
    String APPLY_BACK_CLICKED = "APPLY_BACK_CLICKED";
    String APPLY_STAR_CLICKED = "APPLY_STAR_CLICKED";
    String APPLY_ADSBOX_CLICKED = "APPLY_ADSBOX_CLICKED";
    String APPLY_BIN_CLICKED = "APPLY_BIN_CLICKED";
    String APPLY_APPLY_CLICKED = "APPLY_APPLY_CLICKED";
    String APPLY_CONTACT_CLICKED = "APPLY_CONTACT_CLICKED";

    String APPLYDIALOG_OPEN = "APPLYDIALOG_OPEN";
    String APPLYDIALOG_SURE_CLICKED = "APPLYDIALOG_SURE_CLICKED";
    String APPLYDIALOG_NOPE_CLICKED  = "APPLYDIALOG_NOPE_CLICKED";

    String SETTING_OPEN = "SETTING_OPEN";
    String SETTING_BACK_CLICKED = "SETTING_BACK_CLICKED";
    String SETTING_ADSBOX_CLICKED = "SETTING_ADSBOX_CLICKED";
    String SETTING_GETVIP_CLICKED = "SETTING_GETVIP_CLICKED";
    String SETTING_SHAREAPP_CLICKED = "SETTING_SHAREAPP_CLICKED";
    String SETTING_CHECKUPDATE_CLICKED = "SETTING_CHECKUPDATE_CLICKED";
    String SETTING_POLICY_CLICKED = "SETTING_POLICY_CLICKED";

    String CALL_SHOW = "CALL_SHOW";
    String CALL_ACCETP_CALL = "CALL_ACCETP_CALL";
    String CALL_REJECT_CALL = "CALL_REJECT_CALL";
    String CALL_DISMISS = "CALL_DISMISS";
    String CALL_ANDROID_SMALL_P = "CALL_ANDROID_SMALL_P";
    String CALL_ANDROID_BIGGER_P = "CALL_ANDROID_BIGGER_P";
    String APPLY_ITEM = "APPLY_ITEM";

    String RATE_SHOW = "RATE_SHOW";
    String RATE_NOT_NOW = "RATE_NOT_NOW";
    String RATE_FEED_BACK = "RATE_FEED_BACK";
    String RATE_REVIEW = "RATE_REVIEW";
}
